package com.ritchey.timesheet.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agreements generated by hbm2java
 */
public class Agreements implements java.io.Serializable {

	private Integer ident;
	private Awarded awarded;
	private Job codeJobs;
	private Date lastUpdate;
	private Integer amount;
	private int rate;
	private boolean active;
	private String positionId;
	
	
	@Override
	public String toString() {
		return "Agreements [ident=" + ident + "\\n, lastUpdate=" + lastUpdate + "\\n, amount=" + amount + "\\n, rate="
				+ rate + "\\n, active=" + active + "\\n, positionId=" + positionId + "]";
	}

	public String getPositionId() {
		return positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}
	
	public boolean getActive() {
		return active;
	}

	public boolean isActive() {
		return this.active;
	}
	
	public void setActive(boolean active) {
		this.active = active;
	}

	private Set timesheetses = new HashSet(0);

	public Agreements() {
	}

	public Agreements(Integer ident, Awarded awarded, Job codeJobs,
			Integer rate) {
		this.ident = ident;
		this.awarded = awarded;
		this.codeJobs = codeJobs;
		this.rate = rate;
	}

	public Agreements(Integer ident, Awarded awarded, Job codeJobs,
			Date lastUpdate, Integer amount, Integer rate, Set timesheetses) {
		this.ident = ident;
		this.awarded = awarded;
		this.codeJobs = codeJobs;
		this.lastUpdate = lastUpdate;
		this.amount = amount;
		this.rate = rate;
		this.timesheetses = timesheetses;
	}

	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	public Awarded getAwarded() {
		return this.awarded;
	}

	public void setAwarded(Awarded awarded) {
		this.awarded = awarded;
	}

	public Job getJob() {
		return this.codeJobs;
	}

	public void setJob(Job job) {
		this.codeJobs = job;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public int getRate() {
		return this.rate;
	}
	
	public String getRateFormatted() {
		return Constants.formatFixed(rate);
	}

	public void setRate(int rate) {
		this.rate = rate;
	}

	public Set getTimesheetses() {
		return this.timesheetses;
	}

	public void setTimesheetses(Set timesheetses) {
		this.timesheetses = timesheetses;
	}

}
