package com.ritchey.timesheet.model;

// Generated Feb 6, 2009 11:36:48 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Awarded generated by hbm2java
 */
public class Awarded extends BaseObject implements java.io.Serializable {

	private Integer ident;
	private CodeTerm codeTerm;
	private PeopleProperties person;
	private String year;
	private Awards award;
	private double amount;
	private String statusCode;
	private Date statusDate;
	private String comment;
	private Date lastTs;
	private Set agreementses = new HashSet(0);

	public Awarded() {
	}

	public Awarded(int ident, CodeTerm CodeTerm, 
			String year, Awards awardCode, double amount) {
		this.ident = ident;
		this.codeTerm = CodeTerm;
		this.year = year;
		this.award = awardCode;
		this.amount = amount;
	}

	public Awarded(Integer ident, CodeTerm CodeTerm, 
			String year, Awards awardCode, double amount, String statusCode,
			Date statusDate, String comment, Date lastTs, Set agreementses) {
		this.ident = ident;
		this.codeTerm = CodeTerm;
		this.year = year;
		this.award = awardCode;
		this.amount = amount;
		this.statusCode = statusCode;
		this.statusDate = statusDate;
		this.comment = comment;
		this.lastTs = lastTs;
		this.agreementses = agreementses;
	}

	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	public CodeTerm getCodeTerm() {
		return this.codeTerm;
	}

	public void setCodeTerm(CodeTerm CodeTerm) {
		this.codeTerm = CodeTerm;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Awards getAwards() {
		return this.award;
	}

	public void setAwards(Awards awardCode) {
		this.award = awardCode;
	}

	public double getAmount() {
		return this.amount;
	}
	
	
	public void setAmount(double amount) {
		this.amount = amount;
	}
	
	public int getAmountPennies() {
		return (int)(amount*100);
	}

	public String getAmountFormatted() {
		return Constants.formatPennies((int)(amount*100));
	}
	
	public void setAmountPennies(int amount) {
		this.amount = amount/100.0;
	}

	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public Date getStatusDate() {
		return this.statusDate;
	}
	
	public String getStatusDateFormatted() {
		if (this.statusDate == null)
			return "";
		return Constants.formatDate(this.statusDate);
	}
	
	public void setStatusDateFormatted(String statusDate) {
		
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getLastTs() {
		return this.lastTs;
	}

	public void setLastTs(Date lastTs) {
		this.lastTs = lastTs;
	}

	public Set getAgreementses() {
		return this.agreementses;
	}

	public void setAgreementses(Set agreementses) {
		this.agreementses = agreementses;
	}

	public PeopleProperties getPerson() {
		return person;
	}

	public void setPerson(PeopleProperties person) {
		this.person = person;
	}

}
