package com.ritchey.timesheet.model;

// Generated Feb 6, 2009 11:36:48 AM by Hibernate Tools 3.2.2.GA

/**
 * Awards generated by hbm2java
 */
public class Awards extends BaseObject implements java.io.Serializable {

	private String awardCode;
	private String awardTitle;
	private String longTitle;
	private String ledger;
	private boolean activeAward;
	private boolean isWorkStudy;

	public boolean getIsWorkStudy() {
		return isWorkStudy;
	}

	public void setIsWorkStudy(boolean isWorkStudy) {
		this.isWorkStudy = isWorkStudy;
	}

	public Awards() {
	}

	public Awards(String awardCode, String awardTitle, boolean activeAward) {
		this.awardCode = awardCode;
		this.awardTitle = awardTitle;
		this.activeAward = activeAward;
	}

	public Awards(String awardCode, String awardTitle, String longTitle,
			String ledger, boolean activeAward) {
		this.awardCode = awardCode;
		this.awardTitle = awardTitle;
		this.longTitle = longTitle;
		this.ledger = ledger;
		this.activeAward = activeAward;
	}

	public String getAwardCode() {
		return this.awardCode;
	}

	public void setAwardCode(String awardCode) {
		this.awardCode = awardCode;
	}

	public String getAwardTitle() {
		return this.awardTitle;
	}

	public void setAwardTitle(String awardTitle) {
		this.awardTitle = awardTitle;
	}

	public String getLongTitle() {
		return this.longTitle;
	}

	public void setLongTitle(String longTitle) {
		this.longTitle = longTitle;
	}

	public String getLedger() {
		return this.ledger;
	}

	public void setLedger(String ledger) {
		this.ledger = ledger;
	}

	public boolean isActiveAward() {
		return this.activeAward;
	}

	public void setActiveAward(boolean activeAward) {
		this.activeAward = activeAward;
	}

}
