package com.ritchey.timesheet.model;

// Generated Feb 6, 2009 11:36:48 AM by Hibernate Tools 3.2.2.GA

/**
 * People generated by hbm2java
 */
public class PeopleBasic extends BaseObject implements java.io.Serializable, People {

	private String peopleId;
	private String lastName;
	private String firstName;
	private String middleName;
	private String governmentId;

	@Override
	public String toString() {
		return "PeopleBasic [peopleId=" + peopleId + ", lastName=" + lastName
				+ ", firstName=" + firstName + ", middleName=" + middleName
				+ ", governmentId=" + governmentId + "]";
	}

	public PeopleBasic() {
	}

	public PeopleBasic(String peopleId, String governmentId) {
		this.peopleId = peopleId;
		this.governmentId = governmentId;
	}

	public PeopleBasic(String peopleId, String lastName, String firstName,
			String middleName, String governmentId) {
		this.peopleId = peopleId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.middleName = middleName;
		this.governmentId = governmentId;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#getPeopleId()
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#getPeopleId()
	 */
	public String getPeopleId() {
		return this.peopleId;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#setPeopleId(java.lang.String)
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#setPeopleId(java.lang.String)
	 */
	public void setPeopleId(String peopleId) {
		this.peopleId = peopleId;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#getLastName()
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#getLastName()
	 */
	public String getLastName() {
		return this.lastName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#setLastName(java.lang.String)
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#setLastName(java.lang.String)
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#getFirstName()
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#getFirstName()
	 */
	public String getFirstName() {
		return this.firstName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#setFirstName(java.lang.String)
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#setFirstName(java.lang.String)
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#getMiddleName()
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#getMiddleName()
	 */
	public String getMiddleName() {
		return this.middleName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#setMiddleName(java.lang.String)
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#setMiddleName(java.lang.String)
	 */
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#getGovernmentId()
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#getGovernmentId()
	 */
	public String getGovernmentId() {
		return this.governmentId;
	}

	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.PeopleBasic#setGovernmentId(java.lang.String)
	 */
	/* (non-Javadoc)
	 * @see com.ritchey.timesheet.model.People#setGovernmentId(java.lang.String)
	 */
	public void setGovernmentId(String governmentId) {
		this.governmentId = governmentId;
	}

}
