package com.ritchey.timesheet.model;

// Generated Feb 6, 2009 11:36:48 AM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Timesheets generated by hbm2java
 */
public class Timesheets extends BaseObject implements java.io.Serializable {

	private int ident;
	private Agreements agreements;
	private PayPer payPer;
	private BigDecimal hours;
	private BigDecimal rate;
	private String status;
	private Date entryDate;
	private Date lastUpdate;

	public Timesheets() {
	}

	public Timesheets(int ident, Agreements agreements, PayPer payPer,
			BigDecimal hours, BigDecimal rate, Date entryDate) {
		this.ident = ident;
		this.agreements = agreements;
		this.payPer = payPer;
		this.hours = hours;
		this.rate = rate;
		this.entryDate = entryDate;
	}

	public Timesheets(int ident, Agreements agreements, PayPer payPer,
			BigDecimal hours, BigDecimal rate, String status, Date entryDate,
			Date lastUpdate) {
		this.ident = ident;
		this.agreements = agreements;
		this.payPer = payPer;
		this.hours = hours;
		this.rate = rate;
		this.status = status;
		this.entryDate = entryDate;
		this.lastUpdate = lastUpdate;
	}

	public int getIdent() {
		return this.ident;
	}

	public void setIdent(int ident) {
		this.ident = ident;
	}

	public Agreements getAgreements() {
		return this.agreements;
	}

	public void setAgreements(Agreements agreements) {
		this.agreements = agreements;
	}

	public PayPer getPayPer() {
		return this.payPer;
	}

	public void setPayPer(PayPer payPer) {
		this.payPer = payPer;
	}

	public BigDecimal getHours() {
		return this.hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
